### ISSUE TITLE
[Feature Request] Add option to change express middleware log function

### ISSUE THREAD

**Issue by Chaphasilor** [Olian04/better-logging#54]
**Is your feature request related to a problem? Please describe.**

Currently, the Express logging middleware will output all logs as `info`, however this isn't always wanted.

**Describe the solution you'd like**

Add a way to specify which log function to use. A third parameter in third place would be a possibility that avoids breaking changes; adding it as second parameter would be nicer though (no param behind a long and optional object).

**Describe alternatives you've considered**

Sure, I could write my own middleware. But what's the point in shipping it with the package then \^\^

**Comment by Olian04** [comment]
I agree that this might as well be a feature.

As I see it, there are 3 distinct ways of implementing this:
1. Change the first argument of the middleware from being the entire host obj, to just being the log method. `app.use(expressMiddleware(console.info))`
**Pro:** Clean, No bloat
**Con:** Breaking change
2. Add another argument to the function signature. `app.use(expressMiddleware(console, {}, console.info))`
**Pro:** None breaking
**Con:** Bloat, First argument wont be used at all
3. Reuse config object, and add another property to it. `app.use(expressMiddleware(console, { meta: { method: 'info' } })`
**Pro:** None breaking
**Con:** Might cause confusion since the config object has so far been used to configure WHAT is logged, not HOW it's logged.

I'm leaning towards nr:2 for the time being, but then include nr:1 in the next major release. 

### Relevant code:

Interface: 
https://github.com/Olian04/better-logging/blob/576a9f7a27cc68665b74ba3f72818462c7f23c02/src/express/index.ts#L12-L18

Implementation: 
https://github.com/Olian04/better-logging/blob/576a9f7a27cc68665b74ba3f72818462c7f23c02/src/express/index.ts#L64-L74

**Comment by Chaphasilor** [comment]
> I'm leaning towards nr:2 for the time being, but then include nr:1 in the next major release.

Sounds good 👌🏻 

nr:1 really is a clean solution, didn't think of that \^\^

**Comment by Olian04** [comment]
@Chaphasilor this is a perfect issue to get your feet wet with. Go ahead and open a PR!
Go with nr:2 for now.

**Comment by Chaphasilor** [comment]
> @Chaphasilor this is a perfect issue to get your feet wet with. Go ahead and open a PR!
> Go with nr:2 for now.

welp, guess I have to do that now...  
pretty busy right now, but I can try it.

will only make a draft PR though, because I don't use/have TypeScript :)

**Comment by Olian04** [comment]
You'll have to use typescript to get the code running.

**Comment by Chaphasilor** [comment]
Okay I *really* can't be bothered to setup and learn TypeScript right now, and therefore didn't even manage to properly test this, hence no PR. But here's the changed `express/index.ts`:

<details>

```typescript
import chalk from 'chalk';
import { useValueOrFallback } from '@olian/typescript-helpers';
import { DecoratedInstance } from '../lib/interfaces/decoratedInstance';
import { Color } from '../lib/types/color';
import { DefaultConfig } from '../lib/config';
import { LogFunction } from '../lib/types/logFunction';

export interface IMiddlewareConfigProperty {
  order?: number;
  show?: boolean;
  color?: Color;
}
export interface IConfig {
  method: IMiddlewareConfigProperty;
  ip: IMiddlewareConfigProperty;
  path: IMiddlewareConfigProperty;
  body: IMiddlewareConfigProperty;
  header: IMiddlewareConfigProperty;
}

interface IExpressRequest {
  ip: string;
  path: string;
  body: string;
  method: string;
  headers: object;
}

export const expressMiddleware = (hostObj: DecoratedInstance, config: Partial<IConfig> = {}, logFunction: LogFunction) => {
  if (hostObj === undefined || hostObj.line === undefined) {
    throw new Error('BetterLogging.expressMiddleware requires an object decorated by betterLogging as its first argument.');
  };

  return (req: IExpressRequest, res: unknown, next: (...args: unknown[]) => unknown) => {
    const method = {
      order: useValueOrFallback(config.method, 'order', 1),
      show: useValueOrFallback(config.method, 'show', true),
      color: useValueOrFallback(config.method, 'color', DefaultConfig.color.base),
      value: useValueOrFallback(req, 'method', ''),
    };
    const ip = {
      order: useValueOrFallback(config.ip, 'order', 2),
      show: useValueOrFallback(config.ip, 'show', true),
      color: useValueOrFallback(config.ip, 'color', DefaultConfig.color.base),
      value: useValueOrFallback(req, 'ip', ''),
    };
    const path = {
      order: useValueOrFallback(config.path, 'order', 3),
      show: useValueOrFallback(config.path, 'show', true),
      color: useValueOrFallback(config.path, 'color', chalk.reset),
      value: useValueOrFallback(req, 'path', ''),
    };
    const body = {
      order: useValueOrFallback(config.body, 'order', 4),
      show: useValueOrFallback(config.body, 'show', false),
      color: useValueOrFallback(config.body, 'color', chalk.reset),
      value: useValueOrFallback(req, 'body', ''),
    };
    const header = {
      order: useValueOrFallback(config.header, 'order', 5),
      show: useValueOrFallback(config.header, 'show', false),
      color: useValueOrFallback(config.header, 'color', chalk.reset),
      value: useValueOrFallback(req, 'headers', {}),
    };
    (logFunction != undefined ? logFunction : hostObj.info)(
      [method, ip, path, body, header]
        .sort((a, b) => a.order - b.order)
        .map(obj => !obj.show ? '' : obj.color(`${
          typeof obj.value === 'object'
            ? JSON.stringify(obj.value)
            : obj.value
        }`))
        .filter(v => v.length > 0)
        .join(' ')
    );
    next();
  };
};
```

</details>

I *did* make sure that funky ternary stuff actually works, so the code should be good.  
I had no idea what to use as default value for `logFunction` (using `undefined` threw an error, and I didn't want to reference `hostObj` because it might be undefined), so I just didn't add any default value...

**Comment by Chaphasilor** [comment]
Oh and error handling could be improved of course: check if `logFunction` actually is a function, etc.

**Comment by Olian04** [comment]
This has been implemented in [the latest release]().

I decided to go with the overload approach. Overloading the first argument of the middleware. Allowing the user to either provide the entire host object, or provide just the specific log method. This means that both `app.use(expressMiddleware(console))` and `app.use(expressMiddleware(console.info))` would be valid. However bear in mind that `app.use(expressMiddleware((...args) => console.info(...args)))` would **not** be valid, this was done in order to not break #66
